## Array creation

Common constructors:
- `np.array` — create array from Python lists/tuples
- `np.arange` — like Python `range`, returns evenly spaced values
- `np.linspace` — returns N evenly spaced samples over an interval
- `np.zeros`, `np.ones`, `np.full` — fill with scalar
- `np.eye` — identity matrix
- `np.empty` — allocate without initializing


In [15]:
import numpy as np

# array
a = np.array([1, 2, 3])
b = np.array([[1,2,3],[4,5,6]])
print('a:', a)
print('b:\n', b)

# arange and linspace
r = np.arange(0, 10, 2)   # 0,2,4,6,8
lin = np.linspace(0, 1, 5) # 0.,0.25,0.5,0.75,1.
print('arange:', r)
print('linspace:', lin)

# zeros, ones, full, eye
Z = np.zeros((2,3))
O = np.ones((3,))
F = np.full((2,2), 7)
I = np.eye(4)
print('zeros:\n', Z)
print('ones:\n', O)
print('full:\n', F)
print('eye:\n', I)


a: [1 2 3]
b:
 [[1 2 3]
 [4 5 6]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [1. 1. 1.]
full:
 [[7 7]
 [7 7]]
eye:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Indexing & slicing

NumPy indexing mostly mirrors Python lists but supports multidimensional indexing, slices, boolean masks, and fancy indexing.

Key points:
- `arr[i]`, `arr[i,j]` or `arr[i][j]` — element access
- `arr[start:stop:step]` — slicing
- Negative indices allowed (`-1` last element)
- Slices return **views** (not copies) when possible — modifying a slice may modify the original.


In [16]:
M = np.arange(1,13).reshape(3,4)
print('M:\n', M)
print('M[0,0]:', M[0,0])
print('first row:', M[0])
print('first column:', M[:,0])
print('\nsubmatrix (rows 0..1, cols 1..2):\n', M[0:2, 1:3])

mask = M % 2 == 0
print('\neven elements:', M[mask])

s = M[:, 1:3]
s[0,0] = 33
print('\nmodified slice affects original:\n', M)

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
M[0,0]: 1
first row: [1 2 3 4]
first column: [1 5 9]

submatrix (rows 0..1, cols 1..2):
 [[2 3]
 [6 7]]

even elements: [ 2  4  6  8 10 12]

modified slice affects original:
 [[ 1 33  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Shape manipulation

- `reshape` — change shape (must match size)
- `ravel` / `flatten` — flatten to 1D (`ravel` returns view when possible)
- `transpose` or `.T` — swap axes
- `np.newaxis` / `None` — add new axis
- `np.concatenate`, `np.stack`, `np.vstack`, `np.hstack`


In [17]:
a = np.arange(12)
A = a.reshape(3,4)
print('A:\n', A)
print('A.T:\n', A.T)
print('flatten (ravel):', A.ravel())
print('flatten (flatten):', A.flatten())
print('add axis:', A[:, np.newaxis, 2].shape)

# stack/concat
x = np.array([1,2,3])
y = np.array([4,5,6])
print('concatenate:', np.concatenate([x,y]))
print('vstack:\n', np.vstack([x,y]))
print('stack axis=1:\n', np.stack([x,y], axis=1))


A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A.T:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
flatten (ravel): [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten (flatten): [ 0  1  2  3  4  5  6  7  8  9 10 11]
add axis: (3, 1)
concatenate: [1 2 3 4 5 6]
vstack:
 [[1 2 3]
 [4 5 6]]
stack axis=1:
 [[1 4]
 [2 5]
 [3 6]]


## Math operations

 `np.dot` / `@` / `np.matmul` for matrix multiplication.
Commonly used functions: `sum`, `mean`, `std`, `min`, `max`, `argmax`, `argmin`, `cumsum`, `cumprod`, `dot`, `matmul`, `transpose`, `trace`, `np.linalg` utilities.


In [18]:
X = np.array([[1,2,3],[4,5,6]])
print('X:\n', X)
print('sum all:', X.sum())
print('sum axis=0 (columns):', X.sum(axis=0))
print('mean axis=1 (rows):', X.mean(axis=1))
print('std:', X.std())

# dot / matmul
A = np.array([[10,20],[30,40]])
B = np.array([[50,60],[70,80]])
print('A dot B:\n', A.dot(B))

# inner, outer, einsum
u = np.array([1,2,3])
v = np.array([4,5,6])
print('inner:', np.inner(u,v))
print('outer:\n', np.outer(u,v))
print('einsum (matrix mult):', np.einsum('ik,kj->ij', A, B))

# linear algebra
mat = np.array([[2.,1.],[1.,3.]])
print('determinant:', np.linalg.det(mat))
print('inverse:\n', np.linalg.inv(mat))


X:
 [[1 2 3]
 [4 5 6]]
sum all: 21
sum axis=0 (columns): [5 7 9]
mean axis=1 (rows): [2. 5.]
std: 1.707825127659933
A dot B:
 [[1900 2200]
 [4300 5000]]
inner: 32
outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
einsum (matrix mult): [[1900 2200]
 [4300 5000]]
determinant: 5.000000000000001
inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]


## Random module

Use `np.random` for reproducible pseudo-random numbers. Key functions:
- `np.random.rand` — uniform [0,1)
- `np.random.randn` — standard normal
- `np.random.randint` — random integers
- `np.random.choice` — sample from 1D array

Note: new Generator API (`np.random.default_rng`) is recommended for new code.

In [19]:
print('rand:', np.random.rand(3))
print('randn:', np.random.randn(3))
print('randint 0..9:', np.random.randint(0,10, size=(3,3)))
print('choice:', np.random.choice([10,20,30,40], size=5))

# Recommended: Generator API
rng = np.random.default_rng(40)
print('rng random:', rng.random(35))
print('rng integers:', rng.integers(1, 10, size=4))


rand: [0.82386872 0.32803702 0.40240153]
randn: [-2.37324287 -1.06784612  0.55734954]
randint 0..9: [[2 3 0]
 [0 6 7]
 [5 7 7]]
choice: [40 30 20 40 20]
rng random: [0.7298985  0.69341496 0.94192102 0.05965206 0.69052097 0.92239752
 0.47568318 0.33839069 0.60188281 0.73062776 0.11226259 0.10862828
 0.63726129 0.04232872 0.04771339 0.31927198 0.21120551 0.77624585
 0.79724132 0.17178832 0.13999837 0.37004317 0.52964165 0.54236503
 0.38012403 0.43165694 0.36066174 0.27451715 0.62069279 0.26930308
 0.41861706 0.51260048 0.30393363 0.33424597 0.24268275]
rng integers: [2 3 7 3]
